config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'web#top'
  resources :web do
    collection do
      get "lunchbox"
      get "oseti"
      get "lunch"
      get "dinner"
    end
  end

  resources :reviews, only: [:new, :create] do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to (root_path)
    else
      render action: "new"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(
      :title,
      :text,
      :year,
      :month,
      :day
    )
  end
end

app/controllers/web_controller.rb
class WebController < ApplicationController
  def top
    @comments = Comment.all.order("created_at DESC")
  end

  def lunchbox
  end

  def oseti
  end

  def lunch
  end

  def dinner
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/web_helper.rb
module WebHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title WebSite
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/reviews/new.html.haml
.wrapper
  = form_with model: @comment, url: reviews_path, method: :post, local: true do |f|
    .review__name
      入力欄
    .review-content
      .review-content__title
        題名
      = f.text_field :title, autocomplete: "title", class:"title-box"
      .review-content__title
        感想
      = f.text_area :text, autocomplete: "text", class:"text-box"
      .review-content__year__first
        .review-content__year__first__second
          = f.text_field :year, autocomplete: "year", class:"year-box"
          %p.text 年
          = f.text_field :month, autocomplete: "month", class:"month-day-box"
          %p.text 月
          = f.text_field :day, autocomplete: "day", class:"month-day-box"
          %p.text 日
      = f.submit "投稿する", class: "submit"

app/views/web/_footer.html.haml
.footer-information
  .footer-information__box
    %p 昼  （営業時間  11:00 ~ 14:00）
    %p 夜  （営業時間  17:00 ~ 21:00）
    %p.day 定休日  月曜日
    %p 住所  和歌山市北出島０００ー０
    %p 電話番号 ０７３ー４７３ー１０１０

app/views/web/dinner.html.haml
.wrapper
  .dinnertop
    %p.dinnertop-text 夜の懐石
  = render "web/footer"

app/views/web/lunch.html.haml
.wrapper
  .lunchtop
    %p.lunchtop-text 昼の定食
  .lunch-content-box
    .lunch-contents
      .lunch-contents__image1
      %p.lunch-contents-text お刺身と天ぷら
      %p ¥1000円
    .lunch-contents
      .lunch-contents__image2
      %p.lunch-contents-text お刺身
      %p ¥1000円
    .lunch-contents
      .lunch-contents__image3
      %p.lunch-contents-text 天ぷら
      %p ¥1000円
    .lunch-contents
      .lunch-contents__image
      %p.lunch-contents-text お刺身と天ぷら
      %p ¥1000円
  = render "web/footer"

app/views/web/lunchbox.html.haml
.wrapper
  .lunchbox-top
    %p.web-text 弁当
  .lunchbox-content-box
    .lunchbox-contents
      .lunchbox-contents__image
      %p.lunchbox-contents-text 何々弁当
      %p ¥1000円
    .lunchbox-contents
      .lunchbox-contents__image
      %p.lunchbox-contents-text 何々弁当
      %p ¥1000円
    .lunchbox-contents
      .lunchbox-contents__image
      %p.lunchbox-contents-text 何々弁当
      %p ¥1000円
    .lunchbox-contents
      .lunchbox-contents__image
      %p.lunchbox-contents-text 何々弁当
      %p ¥1000円
  = render "web/footer"

app/views/web/oseti.html.haml
.wrapper
  .oseti-top
    %p.web-text おせち料理
  .oseti-body
    .oseti-body__left.oseti
    .oseti-body__right.oseti
      %p.price 料金
      .oseti-body__right__content
        %p.dan 1段
        %p.dan-price 10000円
      .oseti-body__right__content
        %p.dan 2段
        %p.dan-price 10000円
      .oseti-body__right__content
        %p.dan 3段
        %p.dan-price 10000円

app/views/web/top.html.haml
.wrapper
  .header
    .header__left
      よこい
    .header__center
      %li.list 
        = link_to lunchbox_web_index_path do
          弁当
      %li.list
        = link_to dinner_web_index_path do
          夜のコース
      %li.list
        = link_to lunch_web_index_path do
          昼定食
      %li.list 
        = link_to oseti_web_index_path do
          おせち
    .header__right
      %li.list
        = link_to new_review_path do
          review
  .body
  .footer
    .footer__left
      .footer__left__name
        レビュー
      .footer__left__review-box
        .footer__left__review-box__content
          - @comments.each do |comment|
            .footer__left__review-box__content__title
              %span 題名
              =comment.title
            .footer__left__review-box__content__text
              %p コメント
              =comment.text
            .footer__left__review-box__content__date
              %span 日付け
              %span #{("#{comment.year}" + "/" + "#{comment.month}" + "/" + "#{comment.day}")}
    .footer__right
      %iframe{:height => "596", :src => "https://www.google.com/maps/d/embed?mid=14iTtScIDOdEvJlsX3uhIqWNeHqUrn4Ge", :width => "720"}
  = render "web/footer"